const ACTION_TYPES = {
  //get tasks ACTIONS
  GET_TASKS_ACTION: 'GET_TASKS_ACTION',
  GET_TASKS_REQUEST: 'GET_TASKS_REQUEST',
  GET_TASKS_SUCCESS: ' GET_TASKS_SUCCESS',
  GET_TASKS_ERROR: 'GET_TASKS_ERROR',
};

export default ACTION_TYPES;
